name: Run Web Scraper

on:
  schedule:
    - cron: '0 13 * * *'  # This runs every day at 10am UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
   - name: Setup xvfb
      run: sudo apt-get install -y xvfb

    - name: Run xvfb
      run: Xvfb :99 & export DISPLAY=:99

    - name: Install Puppeteer Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-xcb1 libxcomposite1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0

    - name: Install npm dependencies
      run: npm install  # This assumes you have a package.json with puppeteer as a dependency.

    - name: Run Scraper Script
      run: node final.js

    - name: Commit and Push
      run: |
        git config --global user.name 'Abdin'
        git config --global user.email 'naymul@hotmail.ca'
        git add -A
        git commit -m "Updated JSONs - $(date +'%Y-%m-%d')"
        git push
