name: Run Web Scraper

on:
  schedule:
    - cron: '0 15 * * *'  # This runs every day at 10am UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Puppeteer Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxss1 libxtst6 libglib2.0-0 libnss3 libgtk-3-0 libasound2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libpangocairo-1.0-0 libpango-1.0-0 libxshmfence1

    - name: Install npm dependencies
      run: npm install  # This assumes you have a package.json with puppeteer as a dependency.

    - name: Run Scraper Script
      run: node final.js

    - name: Commit and Push
      run: |
        git config --global user.name 'Abdin'
        git config --global user.email 'naymul@hotmail.ca'
        git add -A
        git commit -m "Updated JSONs - $(date +'%Y-%m-%d')"
        git push
